(ns assignments.sequences)

(defn max-of-pairs
  "Returns the maximum of each pair of elements in coll"
  {:level :easy
   :use   '[map max rest]
   :alternates '[repeat partition]}
  [coll])

(defn filter-by-index
  "Returns elements of coll at even indices"
  {:level :easy
   :use   '[keep-indexed]}
  [pred coll])

(defn collatz-sequence
  "Returns the collatz sequence for n.
   The collatz function takes a number n and returns:
   n/2 if n is even
   3n+1 if n is odd
   The sequence is generated by applying the collatz function to the result
    of the previous application.
   The sequence ends when it reaches 1."
  {:level :easy
   :use   '[iterate take-while]
   :alternates '[(implement your own take-until)]}
  [n])
